### ISSUE TITLE
Hi,最近在做类似的项目，有一些问题想麻烦请教下

### ISSUE THREAD

**Issue by zgzhang** [kingekinge/spark-submit-ui#1]
已经把我的联系方式发送到你的163邮箱了，thanks！

**Comment by kingekinge** [comment]
请问有什么问题吗？那个邮箱我不用很久了

**Comment by loyrevel** [comment]
@zgzhang 实在联系不上作者  不知道能不能联系上你  我用这个项目也有些问题不知道方不方便交流

**Comment by wugui1994** [comment]
> @zgzhang 实在联系不上作者 不知道能不能联系上你 我用这个项目也有些问题不知道方不方便交流
方便留下邮箱吗

**Comment by zgzhang** [comment]
@loyrevel @wugui1994 sorry当年也没有从作者处获得帮助，我自己也几乎不做大数据相关了，但是类似的项目应该很多

**Comment by zgzhang** [comment]
找到一个维护度挺高的项目，细节请两位自己关注下，https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/chinese/job-server.md
