### ISSUE TITLE
email.server.host配置问题

### ISSUE THREAD

**Issue by loyrevel** [kingekinge/spark-submit-ui#2]
email.server.host=
email.default.username=
email.default.password=
email.default.port=

**Comment by loyrevel** [comment]
@kingekinge

**Comment by kingekinge** [comment]
Send a mail message need to configure your own

**Comment by kingekinge** [comment]
Send a mail message need to configure your own

**Comment by Asura7969** [comment]
邮箱配置是配置的什么邮箱？
